server:
  port: "8080"
  mode: "debug"

database:
  driver: "mysql"     # postgres, mysql, sqlite
  host: "localhost"
  port: "3306"
  user: "root"
  password: "password"
  dbname: "inventaris"
  sslmode: "disable"
  # MySQL specific configurations
  charset: "utf8mb4"
  parsetime: true
  loc: "Local"
